### ISSUE TITLE
[Request] - A pm2 script for the app. 

### ISSUE THREAD

**Issue by byparallax** [Catbirby/discord-profiler#1]
Having a lot of windows open might be an issue for some people and their OCD. You stated in your readme that "If this becomes a common concern [you] will make a pm2 file specifically for the script". Would you mind releasing a such script even if it's not a "common" concern for everyone? Thanks!

**Comment by CoalSephos** [comment]
to install pm2: 
`npm install pm2 -g` in the command line

Windows:
![image](https://user-images.githubusercontent.com/31113295/48442823-2dcfe280-e787-11e8-8d62-af8629a7ef14.png)
Linux
![image](https://user-images.githubusercontent.com/31113295/48442842-3e805880-e787-11e8-8e62-cdf5e21c37cb.png)
Mac:
![image](https://oathompsonjones.elixi.re/i/wsvq.png)

to start  script:
`pm2 start main.js` in the command line

Windows:
![image](https://user-images.githubusercontent.com/31113295/48441758-396dda00-e784-11e8-84f8-72fecb2e87e5.png)
Linux:
![image](https://user-images.githubusercontent.com/31113295/48441858-7934c180-e784-11e8-861f-5224c0ade88b.png)
Mac:
![image](https://oathompsonjones.elixi.re/i/w07l.png)

here are docs: http://pm2.keymetrics.io/

**Comment by Catbirby** [comment]
Added Script, just a year late reference readme for updated information.
